// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ObjectstoreTokens struct {
	ID           int64
	Token        string
	Method       string
	Bucket       string
	Key          string
	ExpiresAt    pgtype.Timestamptz
	OneTime      bool
	Used         bool
	Revoked      bool
	Tags         []byte
	CreatedAt    pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	MaxSize      int64
	AllowedTypes []string
	Signature    string
	Scope        string
}
