// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :execrows
DELETE FROM objectstore_tokens
WHERE expires_at < NOW() - interval '7 days'
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkSignatureExists = `-- name: CheckSignatureExists :one
SELECT EXISTS(
    SELECT 1 FROM objectstore_tokens
    WHERE scope = $1 AND signature = $2 AND signature != '' AND revoked = FALSE
) AS exists
`

type CheckSignatureExistsParams struct {
	Scope     string
	Signature string
}

func (q *Queries) CheckSignatureExists(ctx context.Context, arg CheckSignatureExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSignatureExists, arg.Scope, arg.Signature)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findByTags = `-- name: FindByTags :many
SELECT id, token, method, bucket, key, expires_at, one_time, used, revoked, tags, created_at
FROM objectstore_tokens
WHERE tags @> $1::jsonb
ORDER BY created_at DESC
`

type FindByTagsRow struct {
	ID        int64
	Token     string
	Method    string
	Bucket    string
	Key       string
	ExpiresAt pgtype.Timestamptz
	OneTime   bool
	Used      bool
	Revoked   bool
	Tags      []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) FindByTags(ctx context.Context, tags []byte) ([]FindByTagsRow, error) {
	rows, err := q.db.Query(ctx, findByTags, tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByTagsRow
	for rows.Next() {
		var i FindByTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Method,
			&i.Bucket,
			&i.Key,
			&i.ExpiresAt,
			&i.OneTime,
			&i.Used,
			&i.Revoked,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO objectstore_tokens (token, method, bucket, key, expires_at, one_time, tags, max_size, allowed_types, signature, scope)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertTokenParams struct {
	Token        string
	Method       string
	Bucket       string
	Key          string
	ExpiresAt    pgtype.Timestamptz
	OneTime      bool
	Tags         []byte
	MaxSize      int64
	AllowedTypes []string
	Signature    string
	Scope        string
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.Exec(ctx, insertToken,
		arg.Token,
		arg.Method,
		arg.Bucket,
		arg.Key,
		arg.ExpiresAt,
		arg.OneTime,
		arg.Tags,
		arg.MaxSize,
		arg.AllowedTypes,
		arg.Signature,
		arg.Scope,
	)
	return err
}

const consumeOneTimeToken = `-- name: ConsumeOneTimeToken :one
UPDATE objectstore_tokens
SET used = TRUE, used_at = NOW()
WHERE token = $1 AND used = FALSE
RETURNING id
`

func (q *Queries) ConsumeOneTimeToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, consumeOneTimeToken, token)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const revokeByTags = `-- name: RevokeByTags :execrows
UPDATE objectstore_tokens
SET revoked = TRUE, revoked_at = NOW()
WHERE revoked = FALSE
  AND tags @> $1::jsonb
`

func (q *Queries) RevokeByTags(ctx context.Context, tags []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeByTags, tags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE objectstore_tokens
SET revoked = TRUE, revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeToken, token)
	return err
}

const validateToken = `-- name: ValidateToken :one
SELECT id, token, method, bucket, key, expires_at, one_time, used, revoked, max_size, allowed_types
FROM objectstore_tokens
WHERE token = $1
`

type ValidateTokenRow struct {
	ID           int64
	Token        string
	Method       string
	Bucket       string
	Key          string
	ExpiresAt    pgtype.Timestamptz
	OneTime      bool
	Used         bool
	Revoked      bool
	MaxSize      int64
	AllowedTypes []string
}

func (q *Queries) ValidateToken(ctx context.Context, token string) (ValidateTokenRow, error) {
	row := q.db.QueryRow(ctx, validateToken, token)
	var i ValidateTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Method,
		&i.Bucket,
		&i.Key,
		&i.ExpiresAt,
		&i.OneTime,
		&i.Used,
		&i.Revoked,
		&i.MaxSize,
		&i.AllowedTypes,
	)
	return i, err
}
